---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: docker://lpenz/omnilint:0.5.1
  rust:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust.yml@v0.19.0
    with:
      dependencies_debian: 'libclang-dev libz3-dev'
      coveralls: true
      publish_cratesio: false
      publish_github_release: false
